---
name: edax_runner
version: 5.0.1
description: tiny tool for edax-reversi auto learning with learning_list.txt
publish_to: none
homepage: https://github.com/sensuikan1973/edax_runner
issue_tracker: https://github.com/sensuikan1973/edax_runner/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  # cli_util: ^0.4.2 # https://pub.dev/packages/cli_util#displaying-output-and-progress
  libedax4dart: ^7.62.0
  meta: ^1.18.1

dev_dependencies:
  analyzer: ^10.0.1
  pedantic_sensuikan1973: ^5.16.0
