---
# TODO: If https://github.com/dependabot/dependabot-core/issues/2166 has been resolved, this workflow becomes unnecessary.

name: Upgrade Dart Dependencies

on:
  schedule:
    - cron: '0 21 * * *' # everyday, 21:00 (UTC)
  workflow_dispatch:

jobs:
  update_dependencies:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub upgrade && dart pub upgrade --major-versions

      - name: upgrade external binary
        shell: zsh {0}
        run: ./scripts/fetch_libedax_assets.sh

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }} # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: '[Scheduled] `dart pub upgrade && dart pub upgrade --major-versions`'
          title: '[Scheduled] `dart pub upgrade && dart pub upgrade --major-versions`'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)

            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: cron_upgrade_dart_dependencies
          delete-branch: true
          labels: dependencies

      - name: enable auto-merge
        run: gh pr merge ${{ steps.create_pull_request.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PAT }}
