name: dartanalyzer

on:
  pull_request:
    types: [opened, synchronize]
    paths: ['**.dart', 'pubspec.*', 'analysis_options.yaml', '.github/workflows/dartanalyzer.yaml']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', 'analysis_options.yaml', '.github/workflows/dartanalyzer.yaml']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:beta
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: pub get
    - name: analyzer
      run: dartanalyzer --fatal-infos --fatal-warnings .
